# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pirátská strana | FRÝDEK MÍSTEK
email: leonard.varga@pirati.cz
description: >- # this means to ignore newlines until "baseurl:"
  Web místní buňky Pirátů z Frýdku - Místku
url: "https://frydekmistek.pirati.cz/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Localhost setting
baseurl: ""
theme: jekyll-theme-pirati

administrator:
  email: jitka.novotna@pirati.cz # mail kam pujdou chybove vystupy
  email: jakub.petros.it@gmail.com

organization:
  name: Pirátská strana Frýdek - Místek
  shortName: Frýdek - Místek
  contactUid: leonard.varga
  email: leonard.varga@pirati.cz
  phone: +420 774 837 566
  address: |
    Česká Pirátská strana
    Moravskoslezský kraj
    Jugoslávská 3038/40A
    700 30 Ostrava - Zábřeh
  residenceImg:
  mapLink: https://mapy.cz/zakladni?x=18.3416929&y=49.6810111&z=12&source=muni&id=4753&q=frydek%20mistek
  redmineLink: https://redmine.pirati.cz/projects

# homepageTeaser:
#  display: true
#  link: /komunalni-volby/
#  title: Komunální volby 2018

calendar:
  title: Krajský kalendář
  page: https://calendar.google.com/calendar/embed?src=i7ipksvi9b852grgjic8mnhua0%40group.calendar.google.com&ctz=Europe%2FPrague

facebook:
  loadSDK: true
  profilePage: https://www.facebook.com/piratifrm
  appId: 1526197851008996

#twitter:
#  loadSDK: true
#  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

#gplus:
#  profilePage: https://plus.google.com/u/0/+piratskastrana

#flicker:
#  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/frydekmistek.pirati.cz/
  branch: master

# Image banner on the top of the homepage. Useful for promoting current events.
homepageBanner:
  display: true 
  link: /komunalni-volby/
  title: Komunální volby 2018
  breakpoint: 640 # breakpoint in pixels when to start showing `default` instead of `mobile`
  image:
    default: mainpageBanner.png #obrazek vložte do assets/img
    mobile: mainpageBanner.png #obrazek vložte do assets/img

# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/:path/
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "foto"
  -
    scope:
      path: "_program"
    values:
      layout: "page"
      rbar: "garant, program"

emptyArray: []


assets:
  source_maps: false
  compression: false
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-5.0.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
